Neovici/cosmoz-treenode-navigator

.eslintrc.js, bower.json, cosmoz-treenode-navigator.html, cosmoz-treenode-navigator.js, demo/data/multiRootTree.json
Wrong path displayed for search results #3  got solved. The wrong path was mainly displayed when searching a node from the root level. 
List goes below viewport height when filled #1 
Also, issue 1 got solved while working on Performance. Thats why, no additional PR for this one. Hope thats fine.
=> Issue 1 & 3

cosmoz-treenode-button-view.html, cosmoz-treenode-button-view.js, cosmoz-treenode-navigator.html, cosmoz-treenode-navigator.js
The search input gets focused when the user opens the navigator via button view.
=> Issue 2 (focus search input)

.editorconfig, .eslintignore, .eslintrc.json, .gitignore, .travis.yml, analysis.json, bower.json, cosmoz-treenode-button-view.html, cosmoz-treenode-button-view.js, cosmoz-treenode-navigator.html, cosmoz-treenode-navigator.js, demo/index.html, demo/rtl.html, index.html, package.json, polymer.json, test/.eslintrc.json, test/cosmoz-treenode-button-view_test.html, test/cosmoz-treenode-navigator_test.html, test/index.html, yarn.lock
Hybrid element
Fix demos
Improve/fix tests
=> Hybrid element

cosmoz-treenode-button-view.html
See https://github.com/Neovici/cosmoz-treenode-navigator/issues/20
=> Disable "Select" if no node is highlighted [issue-20]

cosmoz-treenode-button-view.html, cosmoz-treenode-button-view.js
When nodesOnPath is undefined set button to same height as line-height normal.
Fixes #25
=> When nodesOnPath is undefined actions div should be hidden

cosmoz-treenode-button-view.html
Add prerender for cosmoz-dialog.
related to  Neovici/cosmoz-dialog#11.
=> Add prerender for cosmoz-dialog

.eslintrc.json, cosmoz-treenode-button-view.html, cosmoz-treenode-button-view.js, cosmoz-treenode-navigator.js, demo/index.html
Pls merge first https://github.com/Neovici/cosmoz-tree/pull/11
@megheaiulian  pls check as discussed /cc @nomego
=> show btn; check for undefined instead

cosmoz-treenode-navigator.js
See https://github.com/Neovici/cosmoz-treenode-navigator/issues/33
And https://github.com/Neovici/cosmoz-frontend/issues/67
=> Set selectedNode to last valid node on path [issue-33]

cosmoz-treenode-navigator.html, cosmoz-treenode-navigator.js
This reverts commit d5e9a2627b0c2fa2448237f230df5e4fffe8e797.
=> Revert "Prevent iron-list from handling selection tap event on itself"

.codeclimate.yml, .eslintignore, .gitignore, .travis.yml, package.json, polymer.json, wct.conf.json, yarn.lock
fixes https://github.com/Neovici/cosmoz-treenode-navigator/issues/39
=> Tests code coverage

bower.json, package-lock.json, yarn.lock
Also updated package-lock.json and yarn.lock
=> update cosmoz-dialog to 2.0.1

cosmoz-treenode-button-view.html, cosmoz-treenode-button-view.js, cosmoz-treenode-navigator.html, cosmoz-treenode-navigator.js
* When node is double clicked it is selected and the dialog closes
=> Double click feature added

cosmoz-treenode-button-view.js, cosmoz-treenode-navigator.js
https://github.com/Neovici/cosmoz-frontend/issues/1314
=> (patch) modulizer erroneously escaped `attr$=` to `attr\$=`

cosmoz-treenode-button-view.js
=> feat: add button and icon parts

.eslintrc, .eslintrc.json, .prettierrc, cosmoz-treenode-navigator.js, helpers.js, package-lock.json, package.json, test/.eslintrc.json
BREAKING CHANGE: Upgrade to cosmoz-utils@5
=> feat: upgrade to cosmoz-utils@5

cosmoz-treenode-navigator.js
[BUG 7794](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/7794)
I removed the label from the search input
=> fix(search): remove label

cosmoz-treenode-navigator.js, helpers.js, test/cosmoz-treenode-navigator.test.js
Improve performance by not normalizing nodes that are not even rendered.
Select node with `Enter` key.
=> feat(cosmoz-treenode-navigator): improve performance

cosmoz-treenode-navigator.js
=> fix: handle missing tree

.github/workflows/workflow.yml, package-lock.json, package.json
=> feat: update virtualizer

cosmoz-treenode-navigator.styles.js, package-lock.json
Added styling that underlines the hovered part of the path which will stay when the user clicks on it
=> fix(styles) - Added styling that underlines the hovered part of the path

.gitignore, CHANGELOG.md, package-lock.json, src/cosmoz-treenode-button-view.ts, src/cosmoz-treenode-navigator.ts, src/util/helpers.ts, stories/cosmoz-treenode-button-view.stories.ts, stories/cosmoz-treenode-navigator.stories.ts
benefits:
- better encapsulation: the navigator now manages its own state internally;
- reduced coupling: the button view doesn't need to know about the internal implementation of the navigator;
LE: add debounce for search
=> feat: add internal management of "nodesOnNodePath" for "cosmoz-treenode-navigator" & debounce search

CHANGELOG.md, package-lock.json, src/cosmoz-treenode-button-view.ts
Add more slots to push more content to the button.
=> feat(button-view): add more slots

src/cosmoz-treenode-navigator.styles.ts
=> feat: new color variable
